items:
- class: a
  id: 1
  instance: a1
  rot: [-0.007514159355931467, 0.0024662406340561554, -0.006314886517946079, 0.9999487873259181]
  trans: [0.014109275325137113, -0.2549919235284838, -0.012897873716692036]
- class: a
  id: 2
  instance: a2
  rot: [-0.006420636863856491, 0.0019331525112685653, -0.0017697126437088834, 0.9999759529412642]
  trans: [0.016422112423566792, -0.2513169663428308, -0.014297253785491626]
- class: a
  id: 3
  instance: a3
  rot: [-0.0006130783416443966, 0.0035847358901212652, 0.012263568510781675, 0.9999181859986979]
  trans: [0.01500558404289548, -0.24911509441764285, -0.01688934356805391]
- class: a
  id: 4
  instance: a4
  rot: [-0.0018818001897802094, 0.002814165084275167, -0.028223447001806297, 0.9995959065253621]
  trans: [0.013341525000115663, -0.24901290473423462, -0.01670203521289745]
- class: b
  id: 5
  instance: b1
  rot: [-0.0008744945369904372, -0.04083928965107312, 0.9991652437240682, -0.0004510143279376473]
  trans: [0.01968909525928666, -0.08760640413385434, -0.025104527123822596]
- class: b
  id: 6
  instance: b2
  rot: [0.0008493863812996493, 0.003722566350300445, -0.011780403299854227, 0.9999233186303016]
  trans: [0.01402889063975718, -0.29538458923739647, -0.017502733418825626]
- class: c
  id: 7
  instance: c1
  rot: [-0.003951916064110463, 0.00292814045855108, 0.0005873966468438681, 0.9999877315837712]
  trans: [-0.0349519064541149, -0.2960639897290475, -0.015529964845627096]
- class: c
  id: 8
  instance: c2
  rot: [0.0004473530311228216, 0.003454403191582144, 0.004526598087802894, 0.9999836883087679]
  trans: [-0.03429497968551998, -0.29286623861795424, -0.017730872339584588]
- class: d
  id: 9
  instance: d1
  rot: [0.0031161829061868394, 0.0032856834618211015, -0.007669682411100949, 0.9999603340433043]
  trans: [-0.0304425498194976, -0.29470591086430287, -0.01991870538845767]
- class: d
  id: 10
  instance: d2
  rot: [0.003294241949093128, 0.000418544693332354, -0.0025692901759918813, 0.9999911857303103]
  trans: [-0.03141621237560252, -0.2818352901661871, -0.025084116895628752]

