items:
- class: trays
  id: 1
  instance: black_tray
  rot: [-0.010684523562438212, 0.0014329860547292583, -0.0036619391011803197, 0.9999351867542365]
  trans: [-0.015840743457712587, -0.2935515150339848, -0.009000351261971051]
- class: trays
  id: 2
  instance: orange_tray
  rot: [-0.00559478256387453, 0.0030181520516779775, -0.006811097125349696, 0.9999565981192409]
  trans: [-0.02143111920346969, -0.2883062460451405, -0.011437094400024326]
- class: flanges
  id: 3
  instance: trapezoidal_flange
  rot: [-0.005667760405302253, 0.0028264466456666398, -0.009896205476109352, 0.9999309740219682]
  trans: [-0.000304264770757446, -0.27834950972503736, -0.011984908474551336]
- class: flanges
  id: 4
  instance: rectangular_flange
  rot: [-0.009588221743786773, 0.0029440243237564717, -0.010159221472285396, 0.9998980892789275]
  trans: [-0.011771168749223456, -0.283139413528425, -0.009678989520638127]
- class: rotating_parts
  id: 5
  instance: shaft
  rot: [0.0008282911283422552, 0.0030224434862668797, -0.02465403021301461, 0.999691131081713]
  trans: [0.016324960187835327, -0.29168258261977625, -0.015764556357028715]
- class: rotating_parts
  id: 6
  instance: ball_bearing
  rot: [-0.00018519313847959238, 0.0037846741524431575, -0.019119746493270143, 0.9998100205734559]
  trans: [-0.003836057407485367, -0.2641597876416293, -0.015484888714543016]
- class: others
  id: 7
  instance: cilinder
  rot: [-0.002928046678956268, 0.002675804151886236, -0.0124857692174273, 0.9999141824085883]
  trans: [0.020717448786317802, -0.24987155363647953, -0.015176506873115236]
- class: others
  id: 8
  instance: irregular
  rot: [-0.0003983237647105869, 0.005470874825066575, -0.005143636643546162, 0.9999717265347586]
  trans: [-0.014328583588330035, -0.2828690432466454, -0.014648951534878682]

